### ISSUE TITLE
Fail to create the API of NAS-Bench-201

### ISSUE THREAD

**Issue by YANGWAGN** [D-X-Y/AutoDL-Projects#78]
First of all, thank you for your excellent work。
When I try to create the API of NAS-Bench-201, there has always been the problem of the process being killed without printing any other messages ?
Can you give relevant suggestions about this question? Thank you！

_The following is a screenshot of the error message：_
![image](https://user-images.githubusercontent.com/50294246/84499419-22d39000-ace5-11ea-8b5d-b952287238af.png)

**Comment by D-X-Y** [comment]
Would you mind to let me know your environment, e.g., Python and PyTorch?
In addition, would you mind to check whether your downloaded file has the md5 string lasting with 096897

**Comment by D-X-Y** [comment]
Temporally closed due to inactive

**Comment by raphaelmemmesheimer** [comment]
Just some context if someone ends up here. The error throws when you initialize the API but have not enough memory. In my test approximately 28GB are nececarry to initialize the API. On  a 16GB machine it could not initialize, on a 32GB it get's tight depending on what is running beside.

**Comment by D-X-Y** [comment]
@raphaelmemmesheimer Thanks for sharing the information! I'm working optimize the memory cost.

**Comment by D-X-Y** [comment]
@YANGWAGN @raphaelmemmesheimer 
Hi, I have optimized the code to be more efficient, please check the document at https://github.com/D-X-Y/AutoDL-Projects/blob/master/docs/NATS-Bench.md#preparation-and-download

In short, NATS-Bench is an extended version of NAS-Bench-201, where we create two search spaces:
- tss, topology search space, the same as NAS-Bench-201
- sss, size search space, a new search space.

by using the following codes, the API can be created by seconds instead of minutes.
```
from nats_bench import create
api = create(None, 'tss', fast_mode=True, verbose=False)
```

Please let me know if you have any questions.
