### ISSUE TITLE
There are some problems with the accuracy of the model

### ISSUE THREAD

**Issue by Trent-tangtao** [D-X-Y/AutoDL-Projects#97]
**Which Algorithm**
Size Search Space
Cifar 10

**Describe the Question**
I get all 32768 architecture candidates‘ acc using the code followed, but all of them in under 90%.
The results in your paper of all method is above 90%. How can I get the result of table 4 in your paper?

from nats_bench import create
model_cifar10_rank = {}
api = create(None, 'sss')
for index in range(32768):
    info = api.get_more_info(index, 'cifar10')
    config = api.get_net_config(index, 'cifar10')
    model_cifar10_rank[config['channels']] = info['test-accuracy']

[models_cifar10_acc_rank 2.txt](https://github.com/D-X-Y/AutoDL-Projects/files/6106710/models_cifar10_acc_rank.2.txt)

**Comment by D-X-Y** [comment]
@Trent-tangtao Hi, thanks for using NATS-Bench.
This is because the default hyperapameter kwargs for get_more_info is `hp=12` (performance of 12 epoch training). You need to use hp=90, if you want to get the performance of full training.
I just added an example for you, please see: https://github.com/D-X-Y/AutoDL-Projects/blob/main/notebooks/NATS-Bench/issue-97.ipynb

**Comment by Trent-tangtao** [comment]
Got it, thank you! And thanks for your excellent work！
